Repository jenkins-x/jenkins-x-versions, pull requests merged in 2019-10, with the labels that each got.

#548 feat: update vault and vault operator to latest versions
  docker/banzaicloud/bank-vaults.yml
  docker/banzaicloud/vault-operator.yml
  docker/vault.yml
Labels: approved, lgtm, size/XS

#553 chore(deps): bump versions
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  quickstarts.yml
Labels: size/S, updatebot

#565 fix: apidocs update
  jx/scripts/update-jx-website.sh
Labels: size/XS

#569 fix: the docs release
  jx/scripts/update-jx-website.sh
Labels: size/XS

#586 fix: make generate-refdocs needs to run in $GOPATH
  jx/scripts/update-jx-website.sh
Labels: approved, lgtm, size/S

#588 fix: Turn on go modules for generating apidocs
  jx/scripts/update-jx-website.sh
Labels: size/XS

#600 feat: add bdd for vault tls
  jenkins-x-boot-vault-tls.yml
  jx/bdd/boot-vault-tls/README.md
  jx/bdd/boot-vault-tls/ci.sh
  jx/bdd/boot-vault-tls/cluster.yaml
  jx/bdd/boot-vault-tls/jx-requirements.yml
  jx/bdd/boot-vault-tls/parameters.yaml
  jx/scripts/upsert_bdd_domains.sh
Labels: approved, lgtm, size/L

#603 fix: reset the domain shard to 0 on 12 o'clock to avoid exceeding the allocated domains
  jx/bdd/boot-vault-tls/ci.sh
Labels: approved, lgtm, size/XS

#611 fix: Add app lifecycle tests to boot-[vault,vault-tls,local] contexts
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-local/jx-requirements.yml
  jx/bdd/boot-vault-tls/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/boot-vault/jx-requirements.yml
Labels: approved, lgtm, size/S
