Repository jenkins-x/jenkins-x-versions, pull requests merged in 2019-03, with the labels that each got.

#67 charts version upgrade of jenkins-x/exposecontroller
  charts/jenkins-x/exposecontroller.yml
Labels: size/XS

#68 fix: upgrade prow
  charts/jenkins-x/prow.yml
Labels: size/XS

#71 upgrade platform
  charts/jenkins-x/jenkins-x-platform.yml
Labels: approved, size/XS

#74 upgrade chart versions
  charts/jenkins-x/dex.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/sso-operator.yml
Labels: size/S

#78 Added eksctl package
  packages/eksctl.yml
Labels: needs-ok-to-test, size/XS

#77 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/tekton.yml
Labels: size/XS

#82 upgrade chart versions
  charts/jenkins-x/dex.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/tekton.yml
Labels: size/S

#97 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
Labels: size/XS

#96 charts version upgrade of stable/grafana
  charts/stable/grafana.yml
Labels: ok-to-test, size/XS

#103 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
Labels: size/XS

#108 Added kubectl to packages versioning
  packages/kubectl.yml
Labels: needs-ok-to-test, size/XS

#117 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
Labels: size/XS

#120 charts version upgrade of jenkins-x/exposecontroller-service
  charts/jenkins-x/exposecontroller-service.yml
Labels: needs-ok-to-test, size/XS

#125 use git organisations + latest jx
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jx/scripts/ci-github.sh
  jx/scripts/ci-gitops.sh
  jx/scripts/ci-ng.sh
  jx/scripts/ci-prow.sh
  jx/scripts/ci-tekton.sh
Labels: size/S

#130 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
Labels: size/S

#133 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
Labels: size/S
