Repository jenkins-x/jenkins-x-versions, pull requests merged in 2019-08, with the labels that each got.

#366 upgrade chart versions
  charts/jenkins-x/environment-controller.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-local.yml
  jenkins-x-boot-vault.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M

#370 chore: Add resource requests/limits and GOPROXY.
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-local.yml
  jenkins-x-boot-vault.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: approved, lgtm, size/L

#369 fix: use a jx verion range for now
  packages/git.yml
  packages/jx.yml
Labels: lgtm, size/XS

#372 fix: add a pipeline
  jenkins-x.yml
Labels: size/XS

#382 upgrade chart versions
  charts/jenkins-x/environment-controller.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/lighthouse.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-local.yml
  jenkins-x-boot-vault.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M

#385 chore: add flagger repo
  charts/repositories.yml
Labels: lgtm, size/XS

#386 chore: add gitUrl for exposecontroller-service
  charts/jenkins-x/exposecontroller-service.yml
Labels: size/XS

#396 fix: Upgrade vault operator version
  charts/jenkins-x/vault-operator.yml
Labels: approved, lgtm, size/XS

#399 chore(deps): bump versions
  charts/bitnami/external-dns.yml
  charts/flagger/flagger.yml
  charts/jenkins-x/environment-controller.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow-knative.yml
  charts/jenkins-x/prow.yml
  charts/jetstack/cert-manager.yml
  charts/stable/external-dns.yml
  charts/stable/grafana.yml
  charts/stable/nginx-ingress.yml
  charts/stable/prometheus.yml
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  jenkins-x-terraform.yml
Labels: approved, lgtm, size/L, updatebot

#398 fix: added step to perform github release
  jenkins-x.yml
Labels: approved, lgtm, size/S

#401 chore(deps): bump versions
  charts/jenkins-x/environment-controller.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/jetstack/cert-manager.yml
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  jenkins-x-terraform-static.yml
  jenkins-x-terraform-tekton.yml
Labels: approved, lgtm, size/L, updatebot

#402 chore: document how to update dependencies
  README.md
Labels: approved, lgtm, size/XS

#405 chore(deps): bump versions
  charts/stable/grafana.yml
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  jenkins-x-terraform-static.yml
  jenkins-x-terraform-tekton.yml
Labels: approved, lgtm, size/M, updatebot

#404 fix: remove the use of the classic git buildpack
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#397 chore: Add kaniko executor image to version stream
  docker/gcr.io/kaniko-project/executor.yml
Labels: approved, lgtm, size/XS

#403 chore: better name for step
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#411 fix: default email for boot bdd tests
  jx/bdd/boot-lh-bs/ci.sh
  jx/bdd/boot-lh-bs/parameters.yaml
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-lh-ghe/parameters.yaml
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-lh/parameters.yaml
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-local/parameters.yaml
  jx/bdd/boot-vault/ci.sh
  jx/bdd/boot-vault/parameters.yaml
Labels: approved, lgtm, size/M

#412 fix: Release pipeline needs an agent. Also don't use pack syntax
  jenkins-x.yml
Labels: approved, lgtm, size/S

#414 chore: Add abayer to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#415 chore: add macox to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#429 chore: add component to git repos used more than once
  charts/flagger/flagger.yml
  charts/flagger/grafana.yml
  charts/jenkins-x/prow-knative.yml
Labels: approved, lgtm, size/XS

#436 chore: fix typo
  git/github.com/jenkins-x-buildpacks/jenkins-x-classic.yml
  git/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.yml
  git/github.com/jenkins-x/jenkins-x-boot-config.yml
Labels: approved, lgtm, size/XS

#437 fix: add the new chart jxboot-resources
  charts/jenkins-x/jxboot-resources.yml
Labels: size/XS
