Repository jenkins-x/jenkins-x-versions, pull requests merged in 2019-05, with the labels that each got.

#236 Update version to v0.7.0 of cert-manager
  charts/stable/cert-manager.yml
Labels: size/XS

#217 charts version upgrade of stable/prometheus
  charts/stable/prometheus.yml
Labels: size/XS

#235 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/sso-operator.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
Labels: size/M

#240 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-tiller.yml
Labels: size/M

#239 Downgrade certmanager to 0.6.7
  charts/stable/cert-manager.yml
Labels: approved, lgtm, size/XS

#241 upgrade chart versions
  charts/jenkins-x/tekton.yml
Labels: size/XS

#245 Adding BDD test for jenkins-x/jx#3860
  jenkins-x-static-gke-us-east1-b.yml
  jx/bdd/static-gke-us-east1-b/README.md
  jx/bdd/static-gke-us-east1-b/ci.sh
  jx/bdd/static-gke-us-east1-b/cluster.yaml
Labels: needs-ok-to-test, size/M

#256 upgrade chart versions
  charts/jenkins-x/exposecontroller.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/tekton.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-tiller.yml
  jx/bdd/gitops/ci.sh
  jx/bdd/knative-build/ci.sh
  jx/bdd/ng/ci.sh
  jx/bdd/static-gke-us-east1-b/ci.sh
  jx/bdd/static/ci.sh
  jx/bdd/tekton/ci.sh
  jx/bdd/tiller/ci.sh
Labels: size/M

#259 feat: flagger version 0.13.2
  charts/flagger/flagger.yml
  charts/flagger/grafana.yml
Labels: size/XS

#257 feat: enable more BDD tests for tekton
  jx/bdd/tekton/ci.sh
Labels: size/S

#260 upgrade chart versions
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/sso-operator.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
Labels: approved, lgtm, size/M

#261 chore: lock the version of the docker images used by the vault
  docker/banzaicloud/bank-vaults.yml
  docker/banzaicloud/vault-operator.yml
  docker/vault.yml
Labels: size/XS

#265 feat: added helm3 bdd tests
  jenkins-x-helm3.yml
  jx/bdd/helm3/README.md
  jx/bdd/helm3/ci.sh
  jx/bdd/helm3/cluster.yaml
Labels: size/M

#266 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-tiller.yml
Labels: size/M

#268 renaming helm3 cluster
  jx/bdd/helm3/cluster.yaml
Labels: size/XS

#237 Adding in eks tests using tekton
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jx/bdd/eksclassic/README.md
  jx/bdd/eksclassic/ci.sh
  jx/bdd/eksclassic/cluster.yaml
  jx/bdd/ekstekton/README.md
  jx/bdd/ekstekton/ci.sh
  jx/bdd/ekstekton/cluster.yaml
Labels: size/L

#274 Update cluster.yaml
  jx/bdd/terraform/cluster.yaml
Labels: size/XS

#275 fix: shorten name of terraform cluster
  jx/bdd/terraform/cluster.yaml
Labels: size/XS
