Repository jenkins-x/jenkins-x-versions, pull requests merged in 2019-04, with the labels that each got.

#137 fix: better cluster names
  jx/bdd/gitops.yaml
  jx/bdd/knative-pipeline.yaml
  jx/bdd/ng.yaml
  jx/bdd/prow.yaml
  jx/bdd/staticjenkins.yaml
  jx/bdd/tekton.yaml
  jx/bdd/terraform.yaml
Labels: size/S

#140 fix: add a prow-knative version
  charts/jenkins-x/prow-knative.yml
Labels: size/XS

#143 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
Labels: size/S

#145 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
Labels: approved, size/S

#150 Added version manifest for external-dns
  OWNERS
  charts/stable/external-dns.yml
Labels: approved, size/XS

#152 charts version upgrade of bitnami/external-dns
  charts/bitnami/external-dns.yml
Labels: approved, lgtm, size/XS

#160 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/knative-build.yml
  charts/jenkins-x/prow.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
Labels: size/S

#162 fix: first spike of docker versions
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
Labels: size/S

#166 upgrade chart versions
  charts/jenkins-x/exposecontroller.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/sso-operator.yml
  charts/jenkins-x/tekton.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
Labels: size/M

#167 bump platform to include latest chartmuseum
  charts/jenkins-x/jenkins-x-platform.yml
Labels: size/XS

#171 fix: use new SA and project
  jx/bdd/gitops.yaml
  jx/bdd/knative-pipeline.yaml
  jx/bdd/ng.yaml
  jx/bdd/prow.yaml
  jx/bdd/staticjenkins.yaml
  jx/bdd/tekton.yaml
  jx/bdd/terraform.yaml
  jx/scripts/ci-github.sh
  jx/scripts/ci-gitops.sh
  jx/scripts/ci-ng.sh
  jx/scripts/ci-prow.sh
  jx/scripts/ci-tekton.sh
  jx/scripts/ci.sh
Labels: approved, size/S

#181 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/tekton.yml
Labels: size/XS

#193 refactor dirs
  README.md
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/sso-operator.yml
  charts/jenkins-x/tekton.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jx/bdd/gitops.yaml
  jx/bdd/gitops/README.md
  jx/bdd/gitops/ci.sh
  jx/bdd/gitops/cluster.yaml
  jx/bdd/knative-build/README.md
  jx/bdd/knative-build/ci.sh
  jx/bdd/knative-build/cluster.yaml
  jx/bdd/ng/README.md
  jx/bdd/ng/ci.sh
  jx/bdd/ng/cluster.yaml
  jx/bdd/static/README.md
  jx/bdd/static/ci.sh
  jx/bdd/static/cluster.yaml
  jx/bdd/tekton/README.md
  jx/bdd/tekton/ci.sh
  jx/bdd/tekton/cluster.yaml
  jx/bdd/terraform/cluster.yaml
Labels: size/L

#194 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
Labels: size/M

#196 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
Labels: size/XS

#198 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
Labels: size/M

#199 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
Labels: size/M

#200 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
Labels: size/XS

#201 fix: add tiller bdd test
  jenkins-x-tiller.yml
  jx/bdd/tiller/README.md
  jx/bdd/tiller/ci.sh
  jx/bdd/tiller/cluster.yaml
Labels: approved, lgtm, size/M

#203 fix: tiller bdd test
  jenkins-x-tiller.yml
Labels: size/XS

#204 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
Labels: size/M

#213 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/sso-operator.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-tiller.yml
Labels: size/M

#216 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/sso-operator.yml
Labels: size/XS

#214 chore: remove execution permission on yaml files
  charts/bitnami/external-dns.yml
  charts/jenkins-x/exposecontroller-service.yml
  charts/stable/grafana.yml
Labels: size/XS

#218 upgrade chart versions
  charts/jenkins-x/exposecontroller.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/prow.yml
Labels: size/XS

#224 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/sso-operator.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-tiller.yml
Labels: size/M

#230 fix: lets switch to a fixed image
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-tiller.yml
Labels: size/S
