Repository jenkins-x/jenkins-x-versions, pull requests merged in 2019-11, with the labels that each got.

#623 fix: add the bucketrepo chart
  charts/jenkins-x/bucketrepo.yml
Labels: size/XS

#625 fix: upgrade bucketrepo and jxboot-resources charts
  charts/jenkins-x/bucketrepo.yml
Labels: approved, lgtm, size/XS

#626 chore: disallow helm 2.15
  packages/helm.yml
Labels: approved, lgtm, size/XS

#633 fix: add a bdd test for bucketrepo
  jenkins-x-bucketrepo.yml
  jx/bdd/bucketrepo/README.md
  jx/bdd/bucketrepo/ci.sh
  jx/bdd/bucketrepo/cluster.yaml
  jx/bdd/bucketrepo/jx-requirements.yml
  jx/bdd/bucketrepo/parameters.yaml
Labels: size/L

#641 chore: Add builder-go-nodejs, switch BDD tests to run on that image
  docker/gcr.io/jenkinsxio/builder-go-nodejs.yml
  jenkins-x-boot-jenkins.yml
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh-gl.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-local.yml
  jenkins-x-boot-vault-tls.yml
  jenkins-x-boot-vault.yml
  jenkins-x-bucketrepo.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-tiller.yml
Labels: approved, size/M, updatebot

#655 fix: try latest boot config
  git/github.com/jenkins-x/jenkins-x-boot-config.yml
Labels: approved, lgtm, size/XS

#660 chore(deps): bump versions
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  quickstarts.yml
Labels: size/XS, updatebot

#675 chore: Update ci.sh for import/qs with local creds
  jx/bdd/boot-jenkins/ci.sh
  jx/bdd/boot-lh-bs/ci.sh
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-lh-gl/ci.sh
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault-tls/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/bucketrepo/ci.sh
  jx/bdd/eksclassic/ci.sh
  jx/bdd/ekstekton/ci.sh
  jx/bdd/gitops/ci.sh
  jx/bdd/helm3/ci.sh
  jx/bdd/knative-build/ci.sh
  jx/bdd/ng/ci.sh
  jx/bdd/static-gke-us-east1-b/ci.sh
  jx/bdd/static/ci.sh
  jx/bdd/tekton/ci.sh
  jx/bdd/terraform-static/ci.sh
  jx/bdd/terraform-tekton/ci.sh
  jx/bdd/tiller/ci.sh
Labels: approved, lgtm, size/L
