Repository jenkins-x/jenkins-x-versions, pull requests merged in 2019-02, with the labels that each got.

#3 bump prow version to fix deck
  charts/jenkins-x/prow.yml
Labels: size/XS

#4 Add flagger addon
  charts/flagger/flagger.yml
  charts/flagger/grafana.yml
Labels: size/XS

#2 docs: polish docs
  README.md
  jx/bdd/knative-pipeline.yaml
  jx/scripts/ci.sh
Labels: size/M

#7 polish docs and use a nicer file name for static jenkins master
  README.md
  charts/jenkins-x/jenkins-x-platform.yml
  jx/bdd/staticjenkins.yaml
  jx/scripts/ci.sh
Labels: size/XS

#9 chore: lock sso-operator, dex and cert-manager charts
  charts/jenkins-x/dex.yml
  charts/jenkins-x/sso-operator.yml
  charts/jenkins-x/vault-operator.yml
  charts/stable/cert-manager.yml
Labels: size/XS

#18 Update SSO-Operator to 1.2.6
  charts/jenkins-x/sso-operator.yml
Labels: approved, size/XS

#23 chore: add to OWNERS
  OWNERS
Labels: approved, size/XS

#24 update jenkins-x-platform
  charts/jenkins-x/jenkins-x-platform.yml
Labels: approved, size/XS

#17 feat: tests for create terraform
  jx/bdd/terraform.yaml
  jx/scripts/ci-github.sh
Labels: approved, lgtm, size/M

#56 rename build pipeline to tekton and upgrade to latest version
  charts/jenkins-x/knative-build-pipeline.yml
Labels: approved, size/XS

#27 fix: add prow bdd tests
  jenkins-x-prow.yml
  jenkins-x-static.yml
  jx/scripts/ci-prow.sh
Labels: approved, size/M

#66 feat: lock exposecontroller chart
  charts/jenkins-x/exposecontroller.yaml
Labels: size/XS

#41 change stable/nginx-ingress to version 1.3.1
  charts/stable/nginx-ingress.yml
Labels: approved, ok-to-test, size/XS
