Repository jenkins-x/jenkins-x-versions, pull requests merged in 2019-06, with the labels that each got.

#273 feat: added terraform based tests
  jenkins-x-terraform.yml
  jx/bdd/terraform/ci.sh
  jx/bdd/terraform/cluster.yaml
Labels: size/M

#281 fix: add the web IDE docker images
  docker/codercom/code-server.yml
  docker/theiaide/theia-full.yml
Labels: size/XS

#276 chore(tekton): Upgrade to Tekton Pipelines 0.4.0 via chart v0.0.39
  charts/jenkins-x/tekton.yml
Labels: size/XS

#282 chore: update vault-operator and vault images
  docker/banzaicloud/bank-vaults.yml
  docker/banzaicloud/vault-operator.yml
  docker/vault.yml
Labels: size/XS

#294 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M

#297 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M

#300 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: approved, size/M

#302 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M
