Repository jenkins-x/jenkins-x-versions, pull requests merged in 2019-07, with the labels that each got.

#313 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
Labels: size/XS

#317 fix: added BDD test for JX Boot with local secrets
  jx/bdd/boot-local/README.md
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-local/cluster.yaml
  jx/bdd/boot-local/jx-requirements.yml
  jx/bdd/boot-local/parameters.yaml
Labels: size/M

#321 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-boot-local.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: approved, size/M

#324 chore: Add remaining builder images to version stream.
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
Labels: approved, lgtm, size/S

#325 feat: Upgrade flagger to 0.17.0
  charts/flagger/flagger.yml
  charts/flagger/grafana.yml
Labels: size/XS

#323 chore: upgrade chart versions
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-boot-local.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M

#322 charts version upgrade of environment-controller
  charts/environment-controller.yml
Labels: needs-ok-to-test, size/XS

#327 upgrade chart versions
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  jenkins-x-boot-local.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M

#330 fix: fix the bdd test for boot local
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-local/jx-requirements.yml
Labels: size/M

#334 chore: Add upper limit to helm version
  packages/helm.yml
Labels: size/XS

#338 fix: add vault, storage + lighthouse bdd tests for boot
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-vault.yml
  jx/bdd/boot-lh-bs/README.md
  jx/bdd/boot-lh-bs/ci.sh
  jx/bdd/boot-lh-bs/cluster.yaml
  jx/bdd/boot-lh-bs/jx-requirements.yml
  jx/bdd/boot-lh-bs/parameters.yaml
  jx/bdd/boot-lh-ghe/README.md
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-lh-ghe/cluster.yaml
  jx/bdd/boot-lh-ghe/jx-requirements.yml
  jx/bdd/boot-lh-ghe/parameters.yaml
  jx/bdd/boot-lh/README.md
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-lh/cluster.yaml
  jx/bdd/boot-lh/jx-requirements.yml
  jx/bdd/boot-lh/parameters.yaml
  jx/bdd/boot-vault/README.md
  jx/bdd/boot-vault/ci.sh
  jx/bdd/boot-vault/cluster.yaml
  jx/bdd/boot-vault/jx-requirements.yml
  jx/bdd/boot-vault/parameters.yaml
Labels: size/L

#328 fix: use the new flagger git repo
  charts/flagger/flagger.yml
Labels: approved, lgtm, size/XS

#342 upgrade chart versions
  charts/jenkins-x/dex.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/jenkins-x/sso-operator.yml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-local.yml
  jenkins-x-boot-vault.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: approved, size/M

#343 polish readme
  README.md
Labels: size/S

#344 chore: work around for regression in verify preinstall
  jx/bdd/boot-lh-bs/ci.sh
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault/ci.sh
Labels: size/M

#345 fix: add lighthouse and environment controller charts
  charts/environment-controller.yml
  charts/jenkins-x/environment-controller.yml
  charts/jenkins-x/lighthouse.yml
  jx/bdd/boot-lh-bs/ci.sh
  jx/bdd/boot-lh-ghe/ci.sh
Labels: size/M

#350 fix: add cert manager
  charts/jetstack/cert-manager.yml
  charts/repositories.yml
Labels: size/XS

#349 Add deletion info
  README.md
Labels: size/S

#348 chore: added precommit configuration
  .pre-commit-config.yaml
Labels: size/XS

#354 fix: bump to Tekton v0.0.42
  charts/jenkins-x/tekton.yml
Labels: size/XS

#356 upgrade chart versions
  charts/jenkins-x/environment-controller.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-local.yml
  jenkins-x-boot-vault.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M

#357 upgrade to latest nginx-ingress
  charts/stable/nginx-ingress.yml
Labels: size/XS

#363 upgrade chart versions
  charts/jenkins-x/environment-controller.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  docker/gcr.io/jenkinsxio/builder-cf.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning-gpu.yml
  docker/gcr.io/jenkinsxio/builder-machine-learning.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-graalvm.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-newman.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-nodejs10x.yml
  docker/gcr.io/jenkinsxio/builder-nodejs8x.yml
  docker/gcr.io/jenkinsxio/builder-python.yml
  docker/gcr.io/jenkinsxio/builder-python2.yml
  docker/gcr.io/jenkinsxio/builder-python37.yml
  docker/gcr.io/jenkinsxio/builder-ruby.yml
  docker/gcr.io/jenkinsxio/builder-rust.yml
  docker/gcr.io/jenkinsxio/builder-scala.yml
  docker/gcr.io/jenkinsxio/builder-swift.yml
  docker/gcr.io/jenkinsxio/builder-terraform.yml
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-local.yml
  jenkins-x-boot-vault.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M

#364 fix: add a version range for git
  packages/git.yml
Labels: size/XS
