Repository jenkins-x/jenkins-x-versions, pull requests merged in 2019-09, with the labels that each got.

#446 fix: Add components for stable versions in the same repo
  charts/stable/cert-manager.yml
  charts/stable/nginx-ingress.yml
Labels: approved, lgtm, size/XS

#457 chore(deps): bump versions
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  quickstarts.yml
Labels: approved, size/L, updatebot

#459 fix: add a git version range
  packages/git.yml
Labels: approved, size/XS

#461 fix: add 2 new BDD tests
  jenkins-x-boot-jenkins.yml
  jenkins-x-boot-lh-gl.yml
  jx/bdd/boot-jenkins/README.md
  jx/bdd/boot-jenkins/ci.sh
  jx/bdd/boot-jenkins/cluster.yaml
  jx/bdd/boot-jenkins/jx-requirements.yml
  jx/bdd/boot-jenkins/parameters.yaml
  jx/bdd/boot-lh-gl/README.md
  jx/bdd/boot-lh-gl/ci.sh
  jx/bdd/boot-lh-gl/cluster.yaml
  jx/bdd/boot-lh-gl/jx-requirements.yml
  jx/bdd/boot-lh-gl/parameters.yaml
Labels: do-not-merge/hold, size/L

#475 chore: Remove create-spring from tekton bdd tests
  jx/bdd/tekton/ci.sh
Labels: approved, lgtm, size/XS

#443 feat: release jx version on merge to master - step 1
  jenkins-x.yml
  jx/scripts/release-jx.sh
Labels: approved, lgtm, size/S

#480 fix: upgrade lighthouse
  charts/jenkins-x/lighthouse.yml
Labels: approved, size/XS

#484 fix: moved JX_VERSION env var to release-jx script
  jenkins-x.yml
  jx/scripts/release-jx.sh
Labels: approved, lgtm, size/XS

#489 fix: remove the output of sa.json
  jx/bdd/boot-jenkins/ci.sh
  jx/bdd/boot-lh-bs/ci.sh
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-lh-gl/ci.sh
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/gitops/ci.sh
  jx/bdd/helm3/ci.sh
  jx/bdd/knative-build/ci.sh
  jx/bdd/ng/ci.sh
  jx/bdd/static-gke-us-east1-b/ci.sh
  jx/bdd/static/ci.sh
  jx/bdd/tekton/ci.sh
  jx/bdd/terraform-static/ci.sh
  jx/bdd/terraform-tekton/ci.sh
  jx/bdd/tiller/ci.sh
Labels: size/M

#490 fix: mount secrets into a non workspace dir to avoid checking out cod…
  jenkins-x-boot-jenkins.yml
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh-gl.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-local.yml
  jenkins-x-boot-vault.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform-static.yml
  jenkins-x-terraform-tekton.yml
  jenkins-x-tiller.yml
  jx/bdd/boot-jenkins/ci.sh
  jx/bdd/boot-lh-bs/ci.sh
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-lh-gl/ci.sh
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/gitops/ci.sh
  jx/bdd/helm3/ci.sh
  jx/bdd/knative-build/ci.sh
  jx/bdd/ng/ci.sh
  jx/bdd/static-gke-us-east1-b/ci.sh
  jx/bdd/static/ci.sh
  jx/bdd/tekton/ci.sh
  jx/bdd/terraform-static/ci.sh
  jx/bdd/terraform-tekton/ci.sh
  jx/bdd/tiller/ci.sh
  jx/scripts/ci-github.sh
Labels: size/L

#491 fix: new BDD GCP project
  README.md
  jx/bdd/boot-jenkins/cluster.yaml
  jx/bdd/boot-jenkins/jx-requirements.yml
  jx/bdd/boot-lh-bs/cluster.yaml
  jx/bdd/boot-lh-bs/jx-requirements.yml
  jx/bdd/boot-lh-ghe/cluster.yaml
  jx/bdd/boot-lh-ghe/jx-requirements.yml
  jx/bdd/boot-lh-gl/cluster.yaml
  jx/bdd/boot-lh-gl/jx-requirements.yml
  jx/bdd/boot-lh/cluster.yaml
  jx/bdd/boot-lh/jx-requirements.yml
  jx/bdd/boot-local/cluster.yaml
  jx/bdd/boot-local/jx-requirements.yml
  jx/bdd/boot-vault/cluster.yaml
  jx/bdd/boot-vault/jx-requirements.yml
  jx/bdd/gitops/cluster.yaml
  jx/bdd/helm3/cluster.yaml
  jx/bdd/knative-build/cluster.yaml
  jx/bdd/ng/cluster.yaml
  jx/bdd/static-gke-us-east1-b/cluster.yaml
  jx/bdd/static/cluster.yaml
  jx/bdd/tekton/cluster.yaml
  jx/bdd/terraform-static/cluster.yaml
  jx/bdd/terraform-tekton/cluster.yaml
  jx/bdd/tiller/cluster.yaml
Labels: approved, lgtm, size/M

#494 chore: adding node12, php5, and php7 builders
  docker/gcr.io/jenkinsxio/builder-nodejs12x.yml
  docker/gcr.io/jenkinsxio/builder-php5x.yml
  docker/gcr.io/jenkinsxio/builder-php7x.yml
Labels: approved, lgtm, size/XS

#499 fix: set the environment variables directly from secrets instead of using step credential command
  jenkins-x-boot-jenkins.yml
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh-gl.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-local.yml
  jenkins-x-boot-vault.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform-static.yml
  jenkins-x-terraform-tekton.yml
  jenkins-x-tiller.yml
  jx/bdd/boot-jenkins/ci.sh
  jx/bdd/boot-lh-bs/ci.sh
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-lh-gl/ci.sh
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/eksclassic/ci.sh
  jx/bdd/ekstekton/ci.sh
  jx/bdd/gitops/ci.sh
  jx/bdd/helm3/ci.sh
  jx/bdd/knative-build/ci.sh
  jx/bdd/ng/ci.sh
  jx/bdd/static-gke-us-east1-b/ci.sh
  jx/bdd/static/ci.sh
  jx/bdd/tekton/ci.sh
  jx/bdd/terraform-static/ci.sh
  jx/bdd/terraform-tekton/ci.sh
  jx/bdd/tiller/ci.sh
  jx/scripts/ci-github.sh
Labels: approved, lgtm, size/L

#502 fix: using a GitHub user as reop owner in order to be able to create …
  jx/bdd/boot-jenkins/ci.sh
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/ekstekton/ci.sh
  jx/bdd/gitops/ci.sh
  jx/bdd/helm3/ci.sh
  jx/bdd/knative-build/ci.sh
  jx/bdd/ng/ci.sh
  jx/bdd/tekton/ci.sh
  jx/bdd/terraform-static/ci.sh
  jx/bdd/terraform-tekton/ci.sh
Labels: approved, lgtm, size/S

#501 chore: lock kube-hunter version used by scan cluster command
  docker/aquasec/kube-hunter.yml
Labels: approved, lgtm, size/XS

#509 fix: Switch back to cb-kubecd for repo owner in tests
  jenkins-x-boot-jenkins.yml
  jenkins-x-boot-lh-bs.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-lh-gl.yml
  jenkins-x-boot-lh.yml
  jenkins-x-boot-local.yml
  jenkins-x-boot-vault.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform-static.yml
  jenkins-x-terraform-tekton.yml
  jenkins-x-tiller.yml
  jx/bdd/boot-jenkins/ci.sh
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/ekstekton/ci.sh
  jx/bdd/gitops/ci.sh
  jx/bdd/helm3/ci.sh
  jx/bdd/knative-build/ci.sh
  jx/bdd/ng/ci.sh
  jx/bdd/tekton/ci.sh
  jx/bdd/terraform-static/ci.sh
  jx/bdd/terraform-tekton/ci.sh
Labels: approved, lgtm, size/M

#497 fix: corrected path to the dependency-matrix
  jx/scripts/release-jx.sh
Labels: approved, lgtm, size/XS

#513 fix: using a GitHub user as reop owner in order to be able to create …
  jx/bdd/boot-jenkins/ci.sh
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/ekstekton/ci.sh
  jx/bdd/gitops/ci.sh
  jx/bdd/helm3/ci.sh
  jx/bdd/knative-build/ci.sh
  jx/bdd/ng/ci.sh
  jx/bdd/tekton/ci.sh
  jx/bdd/terraform-static/ci.sh
  jx/bdd/terraform-tekton/ci.sh
Labels: approved, lgtm, size/S

#523 feat: update jx dependencies on full release of jx
  jenkins-x.yml
  jx/scripts/update-jx-bot.sh
  jx/scripts/update-jx-clients.sh
  jx/scripts/update-jx-website.sh
Labels: approved, lgtm, size/L

#527 fix: resolve line break in pipeline yaml
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#528 fix: only clone the repo if it doesn't exist
  jx/scripts/update-jx-clients.sh
  jx/scripts/update-jx-website.sh
Labels: approved, lgtm, size/S

#532 fix: Only publish when jx is prerelease
  jenkins-x.yml
  jx/scripts/get-jx-prerelease-state.sh
  jx/scripts/update-jx-bot.sh
  jx/scripts/update-jx-clients.sh
  jx/scripts/update-jx-website.sh
Labels: approved, lgtm, size/L

#531 fix: generate updates within a tmp dir
  jx/scripts/update-jx-clients.sh
  jx/scripts/update-jx-website.sh
Labels: approved, do-not-merge/hold, lgtm, size/M

#536 fix: turn off in-cluster discovery of vault URL in `boot-vault`
  jx/bdd/boot-vault/jx-requirements.yml
Labels: approved, lgtm, size/XS

#538 fix: use default workspace
  jenkins-x.yml
  jx/scripts/get-jx-prerelease-state.sh
Labels: approved, lgtm, size/XS

#539 fix: resolve path to jx-docs
  jx/scripts/update-jx-website.sh
Labels: approved, lgtm, size/XS

#541 chore: Split the import tests across contexts
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/tekton/ci.sh
Labels: approved, lgtm, size/S

#542 fix: remove unused jx-ts-client update
  jenkins-x.yml
  jx/scripts/update-jx-clients.sh
Labels: approved, lgtm, size/M
