Repository jenkins-x/jenkins-x-versions, pull requests merged in 2020-07, with the labels that each got.

#1006 chore: pull api docs from jx-api for website
  jx/scripts/update-jx-website.sh
Labels: approved, lgtm, size/S

#1010 feat: add vmware-tanzu velero to versions
  apps/vmware-tanzu/velero/README.MD
  apps/vmware-tanzu/velero/defaults.yml
  apps/vmware-tanzu/velero/values.yaml.gotmpl
  charts/repositories.yml
  charts/vmware-tanzu/velero.yml
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
Labels: approved, lgtm, ok-to-test, size/M

#1037 chore: Add lighthouse-jx chart
  charts/jenkins-x/lighthouse-jx.yml
Labels: approved, lgtm, size/XS
