Repository jenkins-x/jenkins-x-versions, pull requests merged in 2020-06, with the labels that each got.

#971 chore: add Falco chart version
  charts/stable/falco.yml
Labels: approved, lgtm, size/XS

#992 refactor: remove deprecated version flag
  jx/bdd/boot-helm3-mc/ci.sh
  jx/bdd/boot-helm3/ci.sh
  jx/bdd/boot-jenkins/ci.sh
  jx/bdd/boot-lh-bs/ci.sh
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-lh-gl/ci.sh
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault-tls/ci.sh
  jx/bdd/boot-vault-upgrade/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/bucketrepo/ci.sh
  jx/bdd/eksclassic/ci.sh
  jx/bdd/ekstekton/ci.sh
  jx/bdd/gitops/ci.sh
  jx/bdd/helm3/ci.sh
  jx/bdd/knative-build/ci.sh
  jx/bdd/ng/ci.sh
  jx/bdd/static-gke-us-east1-b/ci.sh
  jx/bdd/static/ci.sh
  jx/bdd/tekton/ci.sh
  jx/bdd/terraform-static/ci.sh
  jx/bdd/terraform-tekton/ci.sh
  jx/bdd/tiller/ci.sh
  jx/scripts/ci-github.sh
Labels: approved, lgtm, size/M

#999 feat: Added builder for maven-java-14
  docker/gcr.io/jenkinsxio/build-maven-java14.yml
Labels: approved, lgtm, ok-to-test, size/XS

#1002 chore: Add builder-maven-graalvm-java11
  docker/gcr.io/jenkinsxio/builder-maven-graalvm-java11.yml
Labels: approved, size/XS, updatebot
