Repository jenkins-x/jenkins-x-versions, pull requests merged in 2020-02, with the labels that each got.

#803 fix: add package version files for helmfile and helm 3
  packages/helm3.yml
  packages/helmfile.yml
Labels: approved, lgtm, size/XS

#814 chore: adding hferentschik to OWNERS
  OWNERS
Labels: approved, lgtm, size/M

#811 feat: Added gcloud.yml to lock gcloud version.
  packages/gcloud.yml
Labels: approved, lgtm, ok-to-test, size/XS

#768 feat: Specify kubectl version compatible with JX
  packages/kubectl.yml
Labels: approved, lgtm, size/XS

#822 fix: setting a higher upper limit of 1.17.0 for helm binary
  packages/helm.yml
Labels: approved, lgtm, size/XS

#826 fix: Upgrade to nginx-ingress 1.31.0
  charts/stable/nginx-ingress.yml
Labels: approved, lgtm, size/XS

#829 fix: add BDD test for alpha boot
  apps/jenkins-x/chartmuseum/values.yaml.gotmpl
  apps/jenkins-x/nexus/values.yaml.gotmpl
  jenkins-x-boot-alpha.yml
  jx/bdd/boot-alpha/README.md
  jx/bdd/boot-alpha/ci.sh
Labels: size/L
