Repository jenkins-x/jenkins-x-versions, pull requests merged in 2020-01, with the labels that each got.

#728 fix: remove the existing commands documentation before regenerating it
  jx/scripts/update-jx-website.sh
Labels: approved, lgtm, size/XS

#712 feat: boot upgrade test
  jenkins-x-boot-vault-upgrade.yml
  jx/bdd/boot-vault-upgrade/README.md
  jx/bdd/boot-vault-upgrade/ci.sh
  jx/bdd/boot-vault-upgrade/cluster.yaml
  jx/bdd/boot-vault-upgrade/jx-requirements.yml
  jx/bdd/boot-vault-upgrade/parameters.yaml
Labels: approved, lgtm, size/L

#747 chore: lets not push website updates straight to master, we chould cr…
  jx/scripts/update-jx-website.sh
Labels: approved, lgtm, size/S

#750 fix: pipeline switching to use a branch
  jx/scripts/update-jx-website.sh
Labels: approved, lgtm, size/XS

#756 fix: use the version of boot config from the version stream instead of master
  charts/jenkins-x/environment-controller.yml
  charts/stable/prometheus.yml
  jx/bdd/boot-jenkins/ci.sh
  jx/bdd/boot-lh-bs/ci.sh
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-lh-gl/ci.sh
  jx/bdd/boot-lh/ci.sh
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-vault-tls/ci.sh
  jx/bdd/boot-vault-upgrade/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/bucketrepo/ci.sh
Labels: approved, lgtm, size/M

#791 fix: kustomize version control support
  packages/kustomize.yml
Labels: approved, lgtm, ok-to-test, size/XS

#795 fix: lets avoid deleting the commands index in docs
  charts/gloo/gloo.yml
  charts/repositories.yml
  jx/scripts/update-jx-website.sh
Labels: approved, size/S

#796 fix: first spike of apps defaults for helmfile
  apps/jenkins-x/chartmuseum/values.yaml.gotmpl
  apps/jenkins-x/external-dns/values.tmpl.yaml
  apps/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  apps/jenkins-x/lighthouse/values.yaml.gotmpl
  apps/jenkins-x/tekton/values.yaml.gotmpl
  apps/stable/nginx-ingress/defaults.yml
  apps/stable/nginx-ingress/values.yaml.gotmpl
  apps/stable/velero/README.MD
  apps/stable/velero/defaults.yml
  apps/stable/velero/values.yaml.gotmpl
Labels: approved, lgtm, size/L

#797 fix: try avoid breaking the version update CronJob
  charts/gloo/gloo.yml
Labels: size/XS
